INSERT INTO public.person (name, email, age, gender, country) VALUES('Nirbhay Gupta', 'nirbhay.gupta@email.com',25, 'M', 'IN');
INSERT INTO public.person (name, email, age, gender, country) VALUES('Nirbhay Gupta', 'nirbhay.gupta@email.com',21, 'M', 'DE');
INSERT INTO public.person (name, email, age, gender, country) VALUES('Nirbhay Gupta', 'nirbhay.gupta@email.com',43, 'M', 'PK');
INSERT INTO public.person (name, email, age, gender, country) VALUES('Nirbhay Gupta', 'nirbhay.gupta@email.com',12, 'M', 'IN');
INSERT INTO public.person (name, email, age, gender, country) VALUES('Nirbhay Gupta', 'nirbhay.gupta@email.com',16, 'M', 'IN');
INSERT INTO public.person (name, email, age, gender, country) VALUES('Nirbhay Gupta', 'nirbhay.gupta@email.com',34, 'M', 'DE');
INSERT INTO public.person (name, email, age, gender, country) VALUES('Nirbhay Gupta', 'nirbhay.gupta@email.com',56, 'M', 'PK');
INSERT INTO public.person (name, email, age, gender, country) VALUES('Nirbhay Gupta', 'nirbhay.gupta@email.com',39, 'M', 'IN');
INSERT INTO public.person (name, email, age, gender, country) VALUES('Nirbhay Gupta', 'nirbhay.gupta@email.com',25, 'M', 'DE');
INSERT INTO public.person (name, email, age, gender, country) VALUES('Nirbhay Gupta', 'nirbhay.gupta@email.com',65, 'M', 'PK');
INSERT INTO public.person (name, email, age, gender, country) VALUES('Nirbhay Gupta', 'nirbhay.gupta@email.com',28, 'F', 'IN');
INSERT INTO public.person (name, email, age, gender, country) VALUES('Nirbhay Gupta', 'nirbhay.gupta@email.com',43, 'F', 'DE');
INSERT INTO public.person (name, email, age, gender, country) VALUES('Nirbhay Gupta', 'nirbhay.gupta@email.com',44, 'F', 'PK');
INSERT INTO public.person (name, email, age, gender, country) VALUES('Nirbhay Gupta', 'nirbhay.gupta@email.com',49, 'F', 'IN');
INSERT INTO public.person (name, email, age, gender, country) VALUES('Nirbhay Gupta', 'nirbhay.gupta@email.com',51, 'F', 'IN');
INSERT INTO public.person (name, email, age, gender, country) VALUES('Nirbhay Gupta', 'nirbhay.gupta@email.com',67, 'M', 'IN');
INSERT INTO public.person (name, email, age, gender, country) VALUES('Nirbhay Gupta', 'nirbhay.gupta@email.com',23, 'M', 'DE');
INSERT INTO public.person (name, email, age, gender, country) VALUES('Nirbhay Gupta', 'nirbhay.gupta@email.com',60, 'M', 'PK');
INSERT INTO public.person (name, email, age, gender, country) VALUES('Nirbhay Gupta', 'nirbhay.gupta@email.com',18, 'F', 'IN');
INSERT INTO public.person (name, email, age, gender, country) VALUES('Nirbhay Gupta', 'nirbhay.gupta@email.com',62, 'F', 'DE');

INSERT INTO public.android_app (name, "iconUrl") VALUES('Whatsapp', 'fb');
INSERT INTO public.android_app (name, "iconUrl") VALUES('Facebook', 'fb');
INSERT INTO public.android_app (name, "iconUrl") VALUES('Inshorts', 'fb');
INSERT INTO public.android_app (name, "iconUrl") VALUES('Gmail', 'fb');
INSERT INTO public.android_app (name, "iconUrl") VALUES('Twitter', 'fb');
INSERT INTO public.android_app (name, "iconUrl") VALUES('Tinder', 'fb');
INSERT INTO public.android_app (name, "iconUrl") VALUES('Zomato', 'fb');
INSERT INTO public.android_app (name, "iconUrl") VALUES('Swiggy', 'fb');
INSERT INTO public.android_app (name, "iconUrl") VALUES('Truecaller', 'fb');
INSERT INTO public.android_app (name, "iconUrl") VALUES( 'Slack', 'fb');
INSERT INTO public.android_app (name, "iconUrl") VALUES( 'Uber', 'fb');
INSERT INTO public.android_app (name, "iconUrl") VALUES( 'Ola', 'fb');
INSERT INTO public.android_app (name, "iconUrl") VALUES( 'Voice', 'fb');
INSERT INTO public.android_app (name, "iconUrl") VALUES( 'Paytm', 'fb');
INSERT INTO public.android_app (name, "iconUrl") VALUES( 'Youtube', 'fb');
INSERT INTO public.android_app (name, "iconUrl") VALUES( 'Maps', 'fb');
INSERT INTO public.android_app (name, "iconUrl") VALUES( 'QuizUp', 'fb');
INSERT INTO public.android_app (name, "iconUrl") VALUES( 'Oyo', 'fb');
INSERT INTO public.android_app (name, "iconUrl") VALUES( 'Messenger', 'fb');
INSERT INTO public.android_app (name, "iconUrl") VALUES( 'Telegram', 'fb');