INSERT INTO public.person VALUES(1,'Nirbhay', 'Gupta', 'nirbhay.gupta@email.com',25, 'M', 'IN');
INSERT INTO public.person VALUES(2,'Nirbhay', 'Gupta', 'nirbhay.gupta@email.com',21, 'M', 'DE');
INSERT INTO public.person VALUES(3,'Nirbhay', 'Gupta', 'nirbhay.gupta@email.com',43, 'M', 'PK');
INSERT INTO public.person VALUES(4,'Nirbhay', 'Gupta', 'nirbhay.gupta@email.com',12, 'M', 'IN');
INSERT INTO public.person VALUES(5,'Nirbhay', 'Gupta', 'nirbhay.gupta@email.com',16, 'M', 'IN');
INSERT INTO public.person VALUES(6,'Nirbhay', 'Gupta', 'nirbhay.gupta@email.com',34, 'M', 'DE');
INSERT INTO public.person VALUES(7,'Nirbhay', 'Gupta', 'nirbhay.gupta@email.com',56, 'M', 'PK');
INSERT INTO public.person VALUES(8,'Nirbhay', 'Gupta', 'nirbhay.gupta@email.com',39, 'M', 'IN');
INSERT INTO public.person VALUES(9,'Nirbhay', 'Gupta', 'nirbhay.gupta@email.com',25, 'M', 'DE');
INSERT INTO public.person VALUES(10,'Nirbhay', 'Gupta', 'nirbhay.gupta@email.com',65, 'M', 'PK');
INSERT INTO public.person VALUES(11,'Nirbhay', 'Gupta', 'nirbhay.gupta@email.com',28, 'F', 'IN');
INSERT INTO public.person VALUES(12,'Nirbhay', 'Gupta', 'nirbhay.gupta@email.com',43, 'F', 'DE');
INSERT INTO public.person VALUES(13,'Nirbhay', 'Gupta', 'nirbhay.gupta@email.com',44, 'F', 'PK');
INSERT INTO public.person VALUES(14,'Nirbhay', 'Gupta', 'nirbhay.gupta@email.com',49, 'F', 'IN');
INSERT INTO public.person VALUES(15,'Nirbhay', 'Gupta', 'nirbhay.gupta@email.com',51, 'F', 'IN');
INSERT INTO public.person VALUES(16,'Nirbhay', 'Gupta', 'nirbhay.gupta@email.com',67, 'M', 'IN');
INSERT INTO public.person VALUES(17,'Nirbhay', 'Gupta', 'nirbhay.gupta@email.com',23, 'M', 'DE');
INSERT INTO public.person VALUES(18,'Nirbhay', 'Gupta', 'nirbhay.gupta@email.com',60, 'M', 'PK');
INSERT INTO public.person VALUES(19,'Nirbhay', 'Gupta', 'nirbhay.gupta@email.com',18, 'F', 'IN');
INSERT INTO public.person VALUES(20,'Nirbhay', 'Gupta', 'nirbhay.gupta@email.com',62, 'F', 'DE');

INSERT INTO public.android_app VALUES(1, 'Whatsapp', 'fb');
INSERT INTO public.android_app VALUES(2, 'Facebook', 'fb');
INSERT INTO public.android_app VALUES(3, 'Inshorts', 'fb');
INSERT INTO public.android_app VALUES(4, 'Gmail', 'fb');
INSERT INTO public.android_app VALUES(5, 'Twitter', 'fb');
INSERT INTO public.android_app VALUES(6, 'Tinder', 'fb');
INSERT INTO public.android_app VALUES(7, 'Zomato', 'fb');
INSERT INTO public.android_app VALUES(8, 'Swiggy', 'fb');
INSERT INTO public.android_app VALUES(9, 'Truecaller', 'fb');
INSERT INTO public.android_app VALUES(10, 'Slack', 'fb');
INSERT INTO public.android_app VALUES(11, 'Uber', 'fb');
INSERT INTO public.android_app VALUES(12, 'Ola', 'fb');
INSERT INTO public.android_app VALUES(13, 'Voice', 'fb');
INSERT INTO public.android_app VALUES(14, 'Paytm', 'fb');
INSERT INTO public.android_app VALUES(15, 'Youtube', 'fb');
INSERT INTO public.android_app VALUES(16, 'Maps', 'fb');
INSERT INTO public.android_app VALUES(17, 'QuizUp', 'fb');
INSERT INTO public.android_app VALUES(18, 'Oyo', 'fb');
INSERT INTO public.android_app VALUES(19, 'Messenger', 'fb');
INSERT INTO public.android_app VALUES(20, 'Telegram', 'fb');